(()=>{
const D=window.INTERVIEW_DATA||{};
const view=document.getElementById('view'), root=document.documentElement;
const state={route:'index',stack:[],font:+localStorage.getItem('3v0l-font')||19,theme:localStorage.getItem('3v0l-theme')||'dark',live:0,call:0,step:0,auto:false,speed:+localStorage.getItem('3v0l-speed')||16,search:''};
const $=(s,p=document)=>p.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
const typeLabel={answer:'Réponse',story:'Histoire',scenario:'Scénario',phone:'Appel',phrase:'Phrase',curveball:'Curveball',english:'English'};
const aliases={angry:['angry','mad','frustrated','frustration','furious','upset','énervé','agressif','toxique','insultes'],call:['call','phone','telephone','téléphone','appel','appels','client'],refund:['refund','remboursement','money back','achat'],account:['account','compte','login','connexion','profil','wrong account','mauvais compte'],payment:['payment','paiement','débit','charge','transaction','achat'],transfer:['transfer','transfert','argent','money','recipient','destinataire'],hacked:['hack','hacked','pirate','piraté','security','sécurité'],server:['server','serveur','panne','outage','connexion'],career:['career','emploi','chômage','unemployed','dernier poste'],weakness:['weakness','faiblesse','défaut'],why:['why','pourquoi','motivation','company','entreprise'],epic:['epic','vbucks','fortnite','gaming','player'],taptap:['taptap','transfer','fintech','money'],multitask:['multitask','volume','chat','parallel'],unknown:['unknown','dont know','je sais pas','information','verify','vérifier'],escalation:['escalation','escalade','handoff','senior','équipe']};
const routes=[['index','⌂','INDEX'],['live','⚡','LIVE'],['french','🇫🇷','FRENCH ANSWERS'],['calls','☎','PHONE CALL LAB'],['gaming','🎮','GAMING'],['taptap','💸','TAPTAP SEND'],['stories','🧠','REAL STORIES'],['questions','🎯','CURVEBALLS'],['french-phrases','💬','FRENCH PHRASES'],['english','🇬🇧','ENGLISH BACKUP'],['search','⌕','SEARCH'],['panic','⚠','PANIC MODE'],['help','⌨','CONTROLS']];
const dataItems=()=>[
 ...(D.answers||[]).map(x=>({...x,type:'answer'})),
 ...(D.stories||[]).map(x=>({...x,type:'story'})),
 ...(D.scenarios||[]).map(x=>({...x,type:'scenario'})),
 ...(D.phoneCalls||[]).map(x=>({...x,type:'phone'})),
 ...(D.french||[]).map(x=>({...x,type:'phrase'})),
 ...(D.curveballs||[]).map(x=>({...x,type:'curveball'})),
 ...(D.english||[]).map(x=>({...x,type:'english'}))
];
const allFrench=()=> (D.answers||[]).filter(x=>x.cat==='french');
const coach={
 'angry-player':{title:'Comment gérer ça face à l’intervieweur',good:['Reconnaître la frustration sans prendre l’agressivité personnellement.','Reformuler brièvement le problème pour montrer que tu as compris.','Vérifier les faits avant de promettre un remboursement ou une autre solution.','Donner une prochaine étape claire et rester propriétaire du dossier.'],say:'« Je comprends que la situation soit frustrante, surtout puisque vous avez déjà effectué le paiement. Je vais vérifier ce qui s’est passé et voir quelle solution est possible. »',why:'L’intervieweur cherche surtout à voir ton calme, ton empathie, ton écoute, ton jugement et ta capacité à avancer vers une résolution.',avoid:'Ne dis pas « Calmez-vous », ne promets pas une solution que tu n’as pas encore vérifiée et ne discute pas avec le client sur le ton émotionnel.'},
 'wrong-account-live':{title:'Ce que l’intervieweur évalue',good:['Sécurité et vérification du bon compte.','Compréhension du problème avant toute action.','Utilisation de la bonne procédure sans improviser.'],say:'« Je vais d’abord vérifier les informations du compte et de l’achat afin de comprendre exactement ce qui s’est passé. »',why:'Le point important est de ne pas supposer. Tu identifies d’abord le compte, l’achat et la plateforme, puis tu appliques la procédure autorisée.',avoid:'Ne dis pas que tu vas fusionner ou rembourser avant d’avoir confirmé que le cas est éligible.'},
 'unknown-answer':{title:'Ce que l’intervieweur évalue',good:['Honnêteté.','Vérification de l’information.','Ownership et bonne escalade si nécessaire.'],say:'« Je préfère vérifier cette information plutôt que de vous donner une réponse incorrecte. »',why:'Dire que tu ne sais pas encore est meilleur que d’inventer. Le jugement attendu est de savoir quand chercher, vérifier ou escalader.',avoid:'Évite « Je ne sais pas » sans plan d’action.'},
 'why-tp-fr':{title:'Ce que tu dois démontrer',good:['Lien direct avec Epic Games.','Intérêt réel pour le gaming support.','Correspondance français + anglais + support technique.'],why:'La réponse doit montrer que tu connais déjà le type de problèmes des joueurs et que tu peux être opérationnel rapidement.'},
 'why-tap-fr':{title:'Ce que tu dois démontrer',good:['Empathie et précision.','Compréhension de l’impact d’un transfert d’argent.','Expérience des cas complexes et des escalades.'],why:'Dans un service de transfert, une petite erreur peut avoir une conséquence importante pour le client. Montre donc fiabilité et communication claire.'},
 'channels-fr':{title:'Ce que tu dois démontrer',good:['Polyvalence de canal.','Confort avec appels entrants et sortants.','Capacité à passer de chat à ticket ou téléphone sans perdre le contexte.'],why:'Cette réponse est particulièrement utile pour montrer que tu peux t’adapter au canal imposé par le projet.'},
 'chat-fr':{title:'Ce que tu dois démontrer',good:['Tu ne prends pas l’agressivité personnellement.','Tu filtres l’émotion pour identifier le problème réel.','Tu sais gérer plusieurs chats sans sacrifier la qualité.'],why:'C’est une bonne réponse pour montrer ton comportement sous pression sans parler négativement des clients.'},
 'unemployed-fr':{title:'Ce que tu dois démontrer',good:['Tu es actif.','Tu continues à développer tes compétences.','Tu cherches une opportunité stable et cohérente.'],why:'Reste factuel et tourne rapidement la discussion vers ce que tu peux apporter au poste aujourd’hui.'}
};
const coachFor=x=>coach[x?.id];
function setTheme(){root.dataset.theme=state.theme;localStorage.setItem('3v0l-theme',state.theme);const b=$('[data-action="theme"]');if(b)b.textContent=state.theme==='dark'?'☼':'☾'}
function setFont(n){state.font=Math.max(16,Math.min(30,n));root.style.setProperty('--reader',state.font+'px');localStorage.setItem('3v0l-font',state.font)}
function stopAuto(){if(state.auto){state.auto=false} if(raf){cancelAnimationFrame(raf);raf=null}}
let raf=null,last=0;
function autoTarget(){return state.route==='live'?$('#teleprompter'):state.route==='calls'?$('.call-steps'):null}
function startAuto(){stopAuto();state.auto=true;last=performance.now();const loop=now=>{if(!state.auto)return;const t=autoTarget();if(!t){stopAuto();updateAutoButton();return}const dt=Math.min(80,now-last);last=now;const pxPerSecond=state.speed*3.0;t.scrollTop+=(pxPerSecond*dt)/1000;if(t.scrollTop+t.clientHeight>=t.scrollHeight-2){stopAuto();render({preserve:true});return}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);updateAutoButton()}
function updateAutoButton(){document.querySelectorAll('[data-action="toggle-auto"]').forEach(b=>b.textContent=state.auto?'⏸ Stop auto-scroll':'▶ Auto-scroll')}
function home(){stopAuto();state.stack=[];state.route='index';render()}
function back(){stopAuto();state.route=state.stack.pop()||'index';render()}
function go(r){if(r===state.route)return;stopAuto();state.stack.push(state.route);state.route=r;render()}
window.__3v0lGo=go;
window.__3v0lHome=home;
function globalPicker(){return `<select class="global-picker" id="globalJump" aria-label="Jump to category">${routes.map(r=>`<option value="${r[0]}" ${state.route===r[0]?'selected':''}>${r[1]} ${esc(r[2])}</option>`).join('')}</select>`}
function shellControls(){return `<div class="top-actions"><div class="status-pill"><span class="status-dot"></span>LIVE READY</div>${globalPicker()}<button class="icon-btn" data-action="theme" title="Changer le thème">☼</button><button class="icon-btn" data-action="font-down" title="Réduire le texte">A−</button><button class="icon-btn" data-action="font-up" title="Agrandir le texte">A+</button><button class="icon-btn" data-action="search" title="Recherche rapide">⌕</button></div>`}
function frame(inner){return inner}
function index(){return frame(`<section class="page index-page"><div class="index-hero"><div><div class="eyebrow">3V0L · LIVE INTERVIEW SYSTEM V3</div><h1>French first.<br>Built to survive pressure.</h1><p>One local command center with reliable navigation, working keyboard controls, real French phone roleplays, coach notes and a global jump picker.</p></div><button class="primary-btn hero-live" data-route="live">ENTER LIVE MODE <span>↗</span></button></div><div class="index-grid">${card('live','⚡','LIVE INTERVIEW','Main teleprompter, next answer, auto-scroll and quick jumps.',true)}${card('french','🇫🇷','FRENCH ANSWERS','Ready-to-say answers plus interviewer coaching notes.')} ${card('calls','☎','PHONE CALL LAB',`Full French customer calls · ${(D.phoneCalls||[]).length} scenarios · auto-scroll.`)} ${card('gaming','🎮','GAMING','Epic, V-Bucks, account issues, refunds and player judgment.')} ${card('taptap','💸','TAPTAP SEND','Transfers, urgency, verification, money and support scenarios.')} ${card('stories','🧠','REAL STORIES','Epic, Spotify, Airalo, ENGIE and Beerwulf examples.')} ${card('questions','🎯','CURVEBALLS','Weakness, career gap, proud of, conflict and why-you questions.')} ${card('french-phrases','💬','FRENCH PHRASES','Fast language for empathy, verification, escalation and closing.')} ${card('english','🇬🇧','ENGLISH BACKUP','Emergency reference only.')} </div><div class="index-tools"><button class="tool-card" data-action="search"><b>⌕ SMART SEARCH</b><span>Type one to three rough words.</span></button><button class="tool-card panic-tool" data-route="panic"><b>⚠ PANIC MODE</b><span>Next correct move when your brain freezes.</span></button><button class="tool-card" data-route="help"><b>⌨ CONTROLS</b><span>Keyboard, navigation, scroll and picker.</span></button></div><div class="integrity"><span class="status-dot"></span> Local data loaded · ${(D.phoneCalls||[]).length} phone scenarios · no API required</div></section>`)}
function card(id,icon,title,desc,hot){return `<button class="index-card ${hot?'featured':''}" data-route="${id}"><span class="card-num">${hot?'★':'→'}</span><span class="card-icon">${icon}</span><strong>${title}</strong><span>${desc}</span></button>`}
function live(){const items=allFrench();state.live=Math.max(0,Math.min(state.live,Math.max(0,items.length-1)));const x=items[state.live]||{title:'Aucune réponse',text:'Aucune réponse française chargée.',note:''};const c=coachFor(x);return `<section class="page live-page"><div class="back-row"><button class="back-index" data-action="home">← Index</button><div class="eyebrow">🇫🇷 LIVE MODE · ${state.live+1}/${items.length}</div></div><div class="live-layout"><aside class="live-sidebar"><div class="sidebar-head"><b>QUICK JUMPS</b><span>${state.live+1}/${items.length}</span></div>${items.map((it,i)=>`<button class="topic ${i===state.live?'active':''}" data-live="${i}"><b>${esc(it.title)}</b><small>${esc((it.tags||[]).slice(0,2).join(' · ')||'French')}</small></button>`).join('')}<div class="side-actions"><button data-route="calls">☎ Call Lab</button><button data-action="search">⌕ Search</button><button data-route="panic">⚠ Panic</button></div></aside><main class="reader-shell"><div class="reader-head"><div><div class="eyebrow">SAY THIS</div><h2>${esc(x.title)}</h2></div><div class="reader-controls"><button class="mini-btn" data-action="font-down">A−</button><button class="mini-btn" data-action="font-up">A+</button><button class="mini-btn" data-action="toggle-auto">${state.auto?'⏸ Stop auto-scroll':'▶ Auto-scroll'}</button></div></div><div class="reader-wrap"><article id="teleprompter" class="teleprompter"><div class="reader-topfade"></div><div class="teleprompter-text">${esc(x.text)}</div><div class="reader-bottomfade"></div></article></div>${c?coachBlock(c):''}<div class="reader-foot"><span>${esc(x.note||'Réponse prête à dire directement.')}</span><label>speed <input id="speed" type="range" min="8" max="32" value="${state.speed}"></label></div><div class="live-next"><button data-action="prev-live">← Previous</button><button class="next-big" data-action="next-live">NEXT ANSWER <span>Space</span> →</button><button data-action="next-live">Next →</button></div></main></div></section>`}
function coachBlock(c){return `<section class="coach-box"><div class="coach-head"><div><div class="eyebrow">INTERVIEWER COACH</div><h3>${esc(c.title)}</h3></div></div>${c.say?`<div class="coach-say"><b>PHRASE À DIRE</b><p>${esc(c.say)}</p></div>`:''}<div class="coach-grid">${(c.good||[]).map((g,i)=>`<div><b>${i+1}</b><span>${esc(g)}</span></div>`).join('')}</div><div class="coach-why"><b>POURQUOI</b><span>${esc(c.why||'')}</span></div><div class="coach-avoid"><b>À ÉVITER</b><span>${esc(c.avoid||'')}</span></div></section>`}
function fuzzyToken(a,b){if(a===b)return 1;if(a.includes(b)||b.includes(a))return .75;let prev=[...Array(b.length+1).keys()];for(let i=1;i<=a.length;i++){let cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}const d=prev[b.length],m=Math.max(a.length,b.length);return 1-d/m}
function score(q,x){const nq=norm(q);if(!nq)return 0;const hay=norm([x.title,x.text,x.note,x.company,x.difficulty,...(x.tags||[]),(x.phrases||[]),(x.keywords||[])].flat());const qtokens=nq.split(' ');let s=qtokens.reduce((sum,t)=>sum+Math.max(...hay.split(' ').map(h=>fuzzyToken(t,h)),0),0);for(const [k,vals] of Object.entries(aliases))if(qtokens.some(t=>vals.some(v=>norm(v).includes(t)||t.includes(norm(v)))))s+=1;return s/Math.max(1,qtokens.length)}
function search(){const q=state.search,quick=['angry','call','refund','wrong acct','transfer','career','why'];const results=dataItems().map(x=>({...x,_score:score(q,x)})).filter(x=>q?x._score>0:true).sort((a,b)=>b._score-a._score).slice(0,20);return `<section class="page search-page"><div class="back-row"><button class="back-index" data-action="home">← Index</button><div class="eyebrow">⌕ SEARCH</div></div><div class="search-head"><div><div class="eyebrow">LOW-EFFORT MATCHING</div><h1>What do you remember?</h1><p>One to three words is enough. Searches answers, stories, scenarios, calls and phrases.</p></div><button class="primary-btn" data-route="live">LIVE MODE</button></div><div class="search-box"><input id="searchInput" autocomplete="off" autofocus value="${esc(q)}" placeholder="angry · call · refund · mauvais compte · transfert"><button data-action="clear-search">×</button></div><div class="quick-row">${quick.map(x=>`<button data-query="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="result-count">${results.length} matches</div><div class="results-list">${results.map((x,i)=>`<button class="result-card" data-open-type="${esc(x.type)}" data-open-id="${esc(x.id)}"><span class="result-index">${String(i+1).padStart(2,'0')}</span><span class="result-main"><b>${esc(x.title)}</b><small>${typeLabel[x.type]||x.type} · ${(x.tags||[]).slice(0,5).map(esc).join(' · ')}</small></span><span class="result-arrow">↗</span></button>`).join('')||'<div class="empty">Rien de solide. Essaie angry, call, refund, account ou transfer.</div>'}</div></section>`}
function panic(){return `<section class="page panic-page"><div class="back-row"><button class="back-index" data-action="home">← Index</button><div class="eyebrow">⚠ PANIC MODE</div></div><div class="panic-center"><div class="panic-mark">!</div><h1>Breathe. Listen. Answer.</h1><p>Tu n’as pas besoin de la phrase parfaite. Tu as besoin de la prochaine bonne action.</p><div class="panic-grid"><div><b>1 · ACKNOWLEDGE</b><span>« Je comprends tout à fait votre frustration. »</span></div><div><b>2 · PROBE</b><span>« Pour commencer, pouvez-vous me confirmer… ? »</span></div><div><b>3 · VERIFY</b><span>« Je vais vérifier cela de mon côté. »</span></div><div><b>4 · DON'T INVENT</b><span>« Je préfère vérifier cette information plutôt que de vous donner une mauvaise réponse. »</span></div><div><b>5 · ESCALATE</b><span>« Ce dossier nécessite une vérification supplémentaire. »</span></div><div><b>6 · CLOSE</b><span>« Est-ce que cela répond à votre question ? »</span></div></div><button class="primary-btn" data-route="live">RETURN TO LIVE MODE</button></div></section>`}
function help(){const rows=[['H','Index'],['Esc','Back'],['S','Smart Search'],['Space','Next live answer / next call step'],['Enter','Next phone-call step'],['↑ ↓','Scroll'],['Page Up/Down','Large scroll'],['← →','Previous / next phone scenario'],['T','Toggle auto-scroll in Live or Calls'],['A− / A+','Text size'],['F12','Panic Mode'],['Picker','Jump to any category']];return `<section class="page help-page"><div class="back-row"><button class="back-index" data-action="home">← Index</button><div class="eyebrow">⌨ CONTROLS</div></div><h1>Controls that actually work.</h1><div class="kb-grid">${rows.map(r=>`<div class="kb-card"><kbd>${esc(r[0])}</kbd><span>${esc(r[1])}</span></div>`).join('')}</div></section>`}
function render(opts={}){const oldScroll=opts.preserve?($('.teleprompter')?.scrollTop||0):0;let content='';if(state.route==='index')content=index();else if(state.route==='live')content=live();else if(state.route==='french')content=category('french','🇫🇷','FRENCH ANSWERS');else if(state.route==='calls')content=calls();else if(state.route==='gaming')content=category('gaming','🎮','GAMING');else if(state.route==='taptap')content=category('taptap','💸','TAPTAP SEND');else if(state.route==='stories')content=category('stories','🧠','REAL STORIES');else if(state.route==='questions')content=category('questions','🎯','CURVEBALLS');else if(state.route==='french-phrases')content=category('french-phrases','💬','FRENCH PHRASES');else if(state.route==='english')content=category('english','🇬🇧','ENGLISH BACKUP');else if(state.route==='search')content=search();else if(state.route==='panic')content=panic();else content=help();view.innerHTML=content;bind();setTheme();setFont(state.font);if(oldScroll&&state.route==='live')requestAnimationFrame(()=>$('#teleprompter').scrollTop=oldScroll)}
function bind(){view.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route)));view.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action)));view.querySelectorAll('[data-live]').forEach(b=>b.addEventListener('click',()=>{state.live=+b.dataset.live;render()}));view.querySelector('#speed')?.addEventListener('input',e=>{state.speed=+e.target.value;localStorage.setItem('3v0l-speed',state.speed)});document.getElementById('globalJump')?.addEventListener('change',e=>go(e.target.value))}
function action(a){if(a==='home')return home();if(a==='next-live'){state.live++;if(state.live>=allFrench().length)state.live=0;render();return}if(a==='prev-live'){state.live--;if(state.live<0)state.live=allFrench().length-1;render();return}if(a==='toggle-auto'){state.auto?stopAuto():startAuto();updateAutoButton();return}if(a==='font-up'){setFont(state.font+1);return}if(a==='font-down'){setFont(state.font-1);return}if(a==='theme'){state.theme=state.theme==='dark'?'light':'dark';setTheme();return}if(a==='search'){go('search');return}}
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInput||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement)return;const key=e.key;if(key==='Escape')return back();if(key.toLowerCase()==='h')return home();if(key===' '){e.preventDefault();if(state.route==='live')return action('next-live');if(state.route==='calls')return action('call-next-step')}if(key==='ArrowLeft'){if(state.route==='live')return action('prev-live');if(state.route==='calls')return action('prev-call')}if(key==='ArrowRight'){if(state.route==='calls')return action('next-call')}if(key==='ArrowUp')return scroll(-220);if(key==='ArrowDown')return scroll(220);if(key==='+'){setFont(state.font+1);return}if(key==='-'){setFont(state.font-1);return}});
setTheme();setFont(state.font);render();
})();
