(()=>{
const D=window.INTERVIEW_DATA||{};
const API='http://127.0.0.1:38471';
const refs=[...(D.answers||[]),...(D.stories||[]),...(D.scenarios||[]),...(D.phoneCalls||[])];
let open=localStorage.getItem('3v0l-copilot-open')!=='0';
let running=false, poller=0, lastAt='';
const routeFor=x=>x?.id?.startsWith('call-')?'calls':x?.id?.startsWith('why-tp')||x?.id?.endsWith('-fr')?'french':x?.id?.includes('epic')?'gaming':x?.id?.includes('spotify')?'stories':x?.id?.includes('airalo')?'stories':x?.id?.includes('beerwulf')?'stories':'search';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const findRefs=text=>{
 const t=String(text||'').toLowerCase();
 return refs.map(x=>{const hay=[x.title,x.text,x.company,...(x.tags||[])].join(' ').toLowerCase();let score=0;for(const w of t.split(/\s+/)){if(w.length>2&&hay.includes(w))score++}return {x,score}}).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,6).map(({x})=>({id:x.id,title:x.title,company:x.company||'',tags:(x.tags||[]).slice(0,5)}));
};
function shell(){if(document.getElementById('copilotRail'))return;document.body.classList.toggle('copilot-open',open);const rail=document.createElement('aside');rail.id='copilotRail';rail.className='copilot-rail';rail.innerHTML=`<div class="copilot-head"><div><div class="eyebrow">3V0L · LIVE COPILOT</div><strong>AI interview rail</strong></div><div class="copilot-head-actions"><button class="copilot-icon" data-cp="mock" title="Inject a test question">◇</button><button class="copilot-icon" data-cp="toggle" title="Hide/show rail">${open?'→':'←'}</button></div></div><div class="copilot-status"><span class="cp-dot"></span><span id="cpState">OFFLINE</span><span class="cp-model" id="cpModel">LOCAL</span></div><div class="copilot-body"><section class="cp-section"><div class="cp-label">INTERVIEWER</div><div id="cpTranscript" class="cp-transcript">Waiting for audio / transcript…</div></section><section class="cp-section"><div class="cp-label">DIRECTION</div><div id="cpDirection" class="cp-direction"><div class="cp-empty">No question detected yet.</div></div></section><section class="cp-section cp-say"><div class="cp-label">SAY THIS</div><div id="cpSay" class="cp-say-text">—</div></section><section class="cp-section"><div class="cp-label">BEST REFERENCE</div><button id="cpReference" class="cp-reference" disabled>Select a matching reference when one is detected.</button></section><section class="cp-section"><div class="cp-label">CONFIDENCE</div><div class="cp-confidence"><span id="cpConfidenceBar"></span></div><div id="cpConfidence" class="cp-confidence-text">—</div></section><section class="cp-section cp-tools"><button data-cp="clear">Clear</button><button data-cp="test">Test question</button><button data-cp="settings">Status</button></section></div>`;document.body.appendChild(rail);bind();updateShell();}
function updateShell(){document.body.classList.toggle('copilot-open',open);const b=document.querySelector('[data-cp="toggle"]');if(b)b.textContent=open?'→':'←';}
async function post(path,payload){const r=await fetch(API+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function poll(){try{const r=await fetch(API+'/state',{cache:'no-store'});if(!r.ok)throw new Error();const s=await r.json();if(s.lastEventAt&&s.lastEventAt!==lastAt){lastAt=s.lastEventAt;renderState(s)}document.getElementById('cpState').textContent=s.lastEventAt?'LISTENING':'READY';document.getElementById('cpModel').textContent=s.provider==='requesty'?'REQUESTY':s.provider==='local'?'LOCAL':'NO AI';running=true;document.querySelector('.cp-dot')?.classList.toggle('on',!!s.lastEventAt)}catch{running=false;document.getElementById('cpState').textContent='BRIDGE OFF';document.getElementById('cpModel').textContent='START SERVER';document.querySelector('.cp-dot')?.classList.remove('on')}}
function renderState(s){document.getElementById('cpTranscript').textContent=s.transcript||'—';const dir=(s.direction||[]).map((x,i)=>`<div class="cp-direction-item"><b>${i+1}</b><span>${esc(x)}</span></div>`).join('');document.getElementById('cpDirection').innerHTML=dir||'<div class="cp-empty">No guidance.</div>';document.getElementById('cpSay').textContent=s.sayThis||'—';const c=Math.round((+s.confidence||0)*100);document.getElementById('cpConfidenceBar').style.width=c+'%';document.getElementById('cpConfidence').textContent=c?`${c}% match`:'—';const rb=document.getElementById('cpReference');const x=refs.find(r=>r.id===s.bestReference);rb.disabled=!x;rb.textContent=x?`${x.company?x.company+' · ':''}${x.title}`:'No strong reference yet';rb.dataset.ref=x?.id||'';rb.dataset.rtype=x?.id?.startsWith('call-')?'phone':x?.id?.startsWith('epic-')||x?.id?.startsWith('spotify-')||x?.id?.startsWith('beerwulf-')||x?.id?.startsWith('airalo-')?'story':'answer';}
function sampleContext(text){return findRefs(text)}
async function analyze(text){const context=sampleContext(text);await post('/event',{transcript:text,speaker:'interviewer',final:true,context});}
function openReference(){const b=document.getElementById('cpReference');const id=b?.dataset.ref,rtype=b?.dataset.rtype;if(!id)return;const route=rtype==='phone'?'calls':rtype==='story'?'stories':'french';const routeBtn=document.querySelector(`[data-route="${CSS.escape(route)}"]`);routeBtn?.click();setTimeout(()=>{const card=document.querySelector(`[data-open-id="${CSS.escape(id)}"]`);card?.click()},120);}
function bind(){document.addEventListener('click',e=>{const el=e.target.closest('[data-cp]');if(el){const a=el.dataset.cp;if(a==='toggle'){open=!open;localStorage.setItem('3v0l-copilot-open',open?'1':'0');updateShell();return}if(a==='mock'||a==='test'){analyze('Parlez-moi d’une situation difficile avec un client.');return}if(a==='clear'){post('/clear',{}).catch(()=>{});return}if(a==='settings'){alert(running?'Copilot relay reachable on localhost:38471':'Start the copilot relay first.');return}}if(e.target.id==='cpReference')openReference()});
  poller=setInterval(poll,450);poll();
  window.addEventListener('resize',()=>document.body.classList.toggle('copilot-open',open));
}
shell();
window.__3v0lCopilot={analyze,openReference};
})();