import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {networkInterfaces} from 'node:os';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';
import {startSttServer,sttStatus,setTranscriptHandler} from './stt.mjs';

globalThis.window=globalThis;
try { await import('../data/content.js'); } catch (err) { console.error('Could not load interview data:',err.message); }
const D=globalThis.INTERVIEW_DATA||{};
const HOST=process.env.COPILOT_HOST||'0.0.0.0';
const PORT=Number(process.env.COPILOT_PORT||38471);
const MODEL=process.env.REQUESTY_MODEL||'openai/gpt-4o-mini';
const REQUESTY_URL=process.env.REQUESTY_URL||'https://router.requesty.ai/v1/chat/completions';
const REQUESTY_KEY=process.env.REQUESTY_API_KEY||'';
const REMOTE_PIN=process.env.REMOTE_PIN||'3060';
const ANSWER_LANGUAGE=process.env.ANSWER_LANGUAGE||'fr';
const AUDIO_ENABLED=process.env.AUDIO_ENABLED!=='0';
const commands=[];let commandSeq=0;
let state={connectedAt:new Date().toISOString(),lastEventAt:null,speaker:null,transcript:'',final:false,intent:'idle',direction:[],sayThis:'',bestReference:null,confidence:0,provider:'none',error:null};
const json=(res,status,payload)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'});res.end(JSON.stringify(payload));};
const readBody=req=>new Promise((resolve,reject)=>{const chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)});
const parseBody=async req=>JSON.parse((await readBody(req)).toString('utf8')||'{}');
const auth=body=>String(body?.pin||'')===REMOTE_PIN;
function lanAddresses(){const out=[];for(const list of Object.values(networkInterfaces()))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)out.push(n.address);return out;}
function enqueue(action,payload={}){const cmd={id:++commandSeq,action,...payload,at:new Date().toISOString()};commands.push(cmd);if(commands.length>100)commands.splice(0,commands.length-100);return cmd;}
const allRefs=[...(D.answers||[]),...(D.stories||[]),...(D.scenarios||[]),...(D.phoneCalls||[]),...(D.curveballs||[])];
function tokenize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-z0-9à-ÿœ]+/i).filter(w=>w.length>2);}
function relevantRefs(text){const words=tokenize(text);return allRefs.map(x=>{const hay=tokenize([x.title,x.text,x.company,...(x.tags||[]),...(x.phrases||[])].join(' '));const set=new Set(hay);const hits=words.reduce((n,w)=>n+(set.has(w)?1:0),0);return {x,hits};}).filter(x=>x.hits>0).sort((a,b)=>b.hits-a.hits).slice(0,6).map(({x})=>({id:x.id,title:x.title,company:x.company||'',tags:(x.tags||[]).slice(0,8),text:x.text||'',phrases:x.phrases||[]}));}
function heuristic(text,context=[]){const t=text.toLowerCase();const rules=[{terms:['frustr','angry','énerv','insult','agress'],ref:'angry-player',intent:'difficult_customer',dir:['Reconnaître la frustration','Ne pas prendre l’agressivité personnellement','Reformuler le problème','Vérifier avant de promettre une solution']},{terms:['v-buck','vbucks','fortnite','wrong account','mauvais compte','achat'],ref:'epic-wrong-account',intent:'gaming_account',dir:['Vérifier le compte et la transaction','Identifier la plateforme','Ne pas promettre de remboursement avant vérification']},{terms:['student','étudiant','spotify'],ref:'spotify-student',intent:'account_verification',dir:['Identifier le bon compte','Vérifier la situation','Expliquer la résolution sans improviser']},{terms:['transfer','transfert','argent','mother','mère','recipient','destinataire'],ref:'call-taptap-not-received',intent:'transfer_support',dir:['Vérifier le statut du transfert','Confirmer les informations nécessaires','Donner une prochaine étape claire','Ne pas inventer de délai']},{terms:['phone','téléphone','call','appel','channel','canal'],ref:'channels-fr',intent:'support_channels',dir:['Donner un exemple concret','Montrer ton expérience multi-canaux']}];let best={score:0};for(const r of rules){const score=r.terms.reduce((n,w)=>n+(t.includes(w)?1:0),0);if(score>best.score)best={score,...r};}const contextHit=context.find(x=>best.ref===x.id)||null;if(!best.score)return {intent:'unknown',direction:['Écouter la question jusqu’au bout','Identifier le sujet principal','Répondre avec un exemple réel','Demander une précision si nécessaire'],bestReference:context[0]?.id||null,confidence:.25,sayThis:''};return {intent:best.intent,direction:best.dir,bestReference:contextHit?.id||best.ref,confidence:Math.min(.96,.45+best.score*.15),sayThis:''};}
async function callRequesty(body){if(!REQUESTY_KEY)return null;const referenceText=(body.context||[]).map(x=>`[${x.id}] ${x.title}\n${x.text||x.phrases?.join(' ')||''}`).join('\n\n');const lang=ANSWER_LANGUAGE==='en'?'English':'French';const resp=await fetch(REQUESTY_URL,{method:'POST',headers:{authorization:`Bearer ${REQUESTY_KEY}`,'content-type':'application/json','HTTP-Referer':'http://3v0l.local','X-Title':'3V0L Interview Copilot'},body:JSON.stringify({model:MODEL,messages:[{role:'system',content:`You are the realtime interview assistant for 3V0L. Answer in ${lang} only. Return valid JSON only with keys intent, direction (array of 2-5 short action cues), say_this (a short natural answer Omar can say aloud, maximum 4 sentences), best_reference (one supplied id or null), confidence (0-1). Use ONLY the supplied interview references and Omar's stated experience. Never invent facts, tools, metrics, responsibilities, employers or policies. Prefer a matching reference when one exists.`},{role:'user',content:`Interview question:\n${body.transcript}\n\nProvided interview references:\n${referenceText||'(none)'}\n\nGive the most useful speakable answer.`}],temperature:.12,max_tokens:450})});if(!resp.ok)throw new Error(`Requesty ${resp.status}: ${await resp.text()}`);const data=await resp.json();const text=data?.choices?.[0]?.message?.content||'';try{return JSON.parse(text)}catch{const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start>=0&&end>start)return JSON.parse(text.slice(start,end+1));throw new Error('Requesty returned non-JSON output');}}
async function handleEvent(payload){const transcript=String(payload.transcript||payload.text||'').trim();if(!transcript)return state;const context=Array.isArray(payload.context)&&payload.context.length?payload.context.slice(0,8):relevantRefs(transcript);const base=heuristic(transcript,context);let ai=null;if(payload.final!==false){try{ai=await callRequesty({transcript,speaker:payload.speaker||'interviewer',context});}catch(err){state.error=String(err.message||err);}}const merged=ai||base;state={...state,lastEventAt:new Date().toISOString(),speaker:payload.speaker||'interviewer',transcript,final:payload.final!==false,intent:merged.intent||base.intent,direction:Array.isArray(merged.direction)?merged.direction:base.direction,sayThis:String(merged.say_this||base.sayThis||''),bestReference:merged.best_reference??base.bestReference,confidence:Number.isFinite(+merged.confidence)?+merged.confidence:base.confidence,provider:ai?'requesty':(payload.provider||'local'),error:state.error||null};return state;}
setTranscriptHandler(handleEvent);
if(AUDIO_ENABLED){try{startSttServer();}catch(err){console.error('STT server failed:',err.message);}}
async function serveFile(path,type,res){try{const body=await readFile(join(dirname(fileURLToPath(import.meta.url)),path));res.writeHead(200,{'content-type':type,'cache-control':'no-store'});res.end(body);}catch{return json(res,404,{error:'not found'});}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end();}
if(url.pathname==='/health'&&req.method==='GET')return json(res,200,{ok:true,model:MODEL,requestyConfigured:!!REQUESTY_KEY,stt:sttStatus(),remoteConfigured:true,state});
if(url.pathname==='/state'&&req.method==='GET')return json(res,200,{...state,stt:sttStatus()});
if(url.pathname==='/event'&&req.method==='POST')return json(res,200,await handleEvent(await parseBody(req)));
if(url.pathname==='/clear'&&req.method==='POST'){state={...state,lastEventAt:null,speaker:null,transcript:'',final:false,intent:'idle',direction:[],sayThis:'',bestReference:null,confidence:0,provider:'none',error:null};return json(res,200,state);}
if((url.pathname==='/remote'||url.pathname==='/remote.html')&&req.method==='GET')return serveFile('remote.html','text/html; charset=utf-8',res);
if(url.pathname==='/remote.webmanifest'&&req.method==='GET')return serveFile('remote.webmanifest','application/manifest+json; charset=utf-8',res);
if(url.pathname==='/remote-sw.js'&&req.method==='GET')return serveFile('remote-sw.js','application/javascript; charset=utf-8',res);
if(url.pathname==='/remote/info'&&req.method==='GET'){const hosts=lanAddresses();return json(res,200,{ok:true,port:PORT,hosts,remoteUrl:hosts[0]?`http://${hosts[0]}:${PORT}/remote`:`http://localhost:${PORT}/remote`,audioPort:Number(process.env.AUDIO_PORT||38472)});}
if(url.pathname==='/remote/action'&&req.method==='POST'){const body=await parseBody(req);if(!auth(body))return json(res,401,{error:'invalid remote PIN'});return json(res,200,{ok:true,command:enqueue(String(body.action||''),{value:body.value??null})});}
if(url.pathname==='/remote/commands'&&req.method==='GET'){const after=Number(url.searchParams.get('after')||0);return json(res,200,{commands:commands.filter(c=>c.id>after)});}
return json(res,404,{error:'not found'});}catch(err){return json(res,500,{error:String(err.message||err)});}});
server.listen(PORT,HOST,()=>{const hosts=lanAddresses();console.log(`3V0L Copilot relay listening on http://${HOST}:${PORT}`);console.log(`3V0L Remote: ${hosts[0]?`http://${hosts[0]}:${PORT}/remote`:`http://localhost:${PORT}/remote`}`);console.log(`Audio/STT: ${hosts[0]?`${hosts[0]}:${Number(process.env.AUDIO_PORT||38472)}`:`localhost:${Number(process.env.AUDIO_PORT||38472)}`}`);console.log(`Requesty: ${REQUESTY_KEY?'configured':'not configured'}`);});
