import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {networkInterfaces} from 'node:os';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';
import {startSttServer,sttStatus,setTranscriptHandler,setSttProviderEnabled,sttProviderControls} from './stt.mjs';

globalThis.window=globalThis;
try { await import('../data/content.js'); } catch (err) { console.error('Could not load interview data:',err.message); }
const D=globalThis.INTERVIEW_DATA||{};
const HOST=process.env.COPILOT_HOST||'0.0.0.0';
const PORT=Number(process.env.COPILOT_PORT||38471);

// LLM backends. Cerebras is the preferred fast free-tier backend; Requesty remains the fallback.
const CEREBRAS_MODEL=process.env.CEREBRAS_MODEL||'gpt-oss-120b';
const CEREBRAS_URL=process.env.CEREBRAS_URL||'https://api.cerebras.ai/v1/chat/completions';
const CEREBRAS_KEY=process.env.CEREBRAS_API_KEY||'';
const REQUESTY_MODEL=process.env.REQUESTY_MODEL||'openai/gpt-4o-mini';
const REQUESTY_URL=process.env.REQUESTY_URL||'https://router.requesty.ai/v1/chat/completions';
const REQUESTY_KEY=process.env.REQUESTY_API_KEY||'';
const LLM_PRIMARY=String(process.env.LLM_PRIMARY||'cerebras').toLowerCase();
const REMOTE_PIN=process.env.REMOTE_PIN||'3060';
const ANSWER_LANGUAGE=process.env.ANSWER_LANGUAGE||'fr';
const AUDIO_ENABLED=process.env.AUDIO_ENABLED!=='0';
let llmEnabled = true;
const commands=[];let commandSeq=0;
let state={connectedAt:new Date().toISOString(),lastEventAt:null,speaker:null,transcript:'',final:false,intent:'idle',direction:[],sayThis:'',bestReference:null,confidence:0,provider:'none',error:null};
const json=(res,status,payload)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'});res.end(JSON.stringify(payload));};
const readBody=req=>new Promise((resolve,reject)=>{const chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)});
const parseBody=async req=>JSON.parse((await readBody(req)).toString('utf8')||'{}');
const auth=body=>String(body?.pin||'')===REMOTE_PIN;
function lanAddresses(){const out=[];for(const list of Object.values(networkInterfaces()))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)out.push(n.address);return out;}
function enqueue(action,payload={}){const cmd={id:++commandSeq,action,...payload,at:new Date().toISOString()};commands.push(cmd);if(commands.length>100)commands.splice(0,commands.length-100);return cmd;}
const allRefs=[...(D.answers||[]),...(D.stories||[]),...(D.scenarios||[]),...(D.phoneCalls||[]),...(D.curveballs||[])];
function tokenize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-z0-9à-ÿœ]+/i).filter(w=>w.length>2);}
function relevantRefs(text){const words=tokenize(text);return allRefs.map(x=>{const hay=tokenize([x.title,x.text,x.company,...(x.tags||[]),...(x.phrases||[])].join(' '));const set=new Set(hay);const hits=words.reduce((n,w)=>n+(set.has(w)?1:0),0);return {x,hits};}).filter(x=>x.hits>0).sort((a,b)=>b.hits-a.hits).slice(0,6).map(({x})=>({id:x.id,title:x.title,company:x.company||'',tags:(x.tags||[]).slice(0,8),text:x.text||'',phrases:x.phrases||[]}));}
function heuristic(text,context=[]){const t=text.toLowerCase();const rules=[
  {terms:['comdata','iris','engie','jira','centre d excellence','centre d’excellence','specialise','spécialisé','dossier spécialisé'],ref:'comdata-iris',intent:'comdata_experience',dir:['Mettre en avant le support back-office et les dossiers spécialisés','Expliquer que les cas bloqués nécessitaient une analyse plus poussée','Mentionner Jira et l’escalade au Centre d’Excellence lorsque nécessaire'],say:'Oui. Chez Comdata, j’ai travaillé d’abord sur le traitement de dossiers back-office pour ENGIE. Après quelques mois, mes bons résultats m’ont permis de prendre en charge des dossiers plus spécialisés via Iris. Il fallait comprendre pourquoi un dossier était bloqué, corriger ce qui pouvait l’être et, lorsque nécessaire, transmettre le dossier au Centre d’Excellence via Jira.'},
  {terms:['frustr','angry','énerv','insult','agress'],ref:'angry-player',intent:'difficult_customer',dir:['Reconnaître la frustration','Ne pas prendre l’agressivité personnellement','Reformuler le problème','Vérifier avant de promettre une solution']},
  {terms:['v-buck','vbucks','fortnite','wrong account','mauvais compte','achat'],ref:'epic-wrong-account',intent:'gaming_account',dir:['Vérifier le compte et la transaction','Identifier la plateforme','Ne pas promettre de remboursement avant vérification']},
  {terms:['student','étudiant','spotify'],ref:'spotify-student',intent:'account_verification',dir:['Identifier le bon compte','Vérifier la situation','Expliquer la résolution sans improviser']},
  {terms:['transfer','transfert','argent','mother','mère','recipient','destinataire'],ref:'call-taptap-not-received',intent:'transfer_support',dir:['Vérifier le statut du transfert','Confirmer les informations nécessaires','Donner une prochaine étape claire','Ne pas inventer de délai']},
  {terms:['phone','téléphone','call','appel','channel','canal'],ref:'channels-fr',intent:'support_channels',dir:['Donner un exemple concret','Montrer ton expérience multi-canaux']}
];let best={score:0};for(const r of rules){const score=r.terms.reduce((n,w)=>n+(t.includes(w)?1:0),0);if(score>best.score)best={score,...r};}const contextHit=context.find(x=>best.ref===x.id)||null;if(!best.score)return {intent:'unknown',direction:['Écouter la question jusqu’au bout','Identifier le sujet principal','Répondre avec un exemple réel','Demander une précision si nécessaire'],bestReference:context[0]?.id||null,confidence:.25,sayThis:''};return {intent:best.intent,direction:best.dir,bestReference:contextHit?.id||best.ref,confidence:Math.min(.96,.45+best.score*.15),sayThis:best.sayThis||''};}
function providerConfig(name){if(name==='cerebras')return {name:'cerebras',label:'Cerebras GPT-OSS-120B',url:CEREBRAS_URL,key:CEREBRAS_KEY,model:CEREBRAS_MODEL};if(name==='requesty')return {name:'requesty',label:`Requesty ${REQUESTY_MODEL}`,url:REQUESTY_URL,key:REQUESTY_KEY,model:REQUESTY_MODEL};return null;}
function providerOrder(){const first=LLM_PRIMARY==='requesty'?'requesty':'cerebras';return [first,first==='cerebras'?'requesty':'cerebras'];}
function buildPayload(body,model){const referenceText=(body.context||[]).map(x=>`[${x.id}] ${x.title}\n${x.text||x.phrases?.join(' ')||''}`).join('\n\n');const lang=ANSWER_LANGUAGE==='en'?'English':'French';return {model,messages:[{role:'system',content:`You are the realtime interview assistant for 3V0L. Answer in ${lang} only. Use ONLY the supplied interview references and Omar's stated experience. Never invent facts, tools, metrics, responsibilities, employers or policies. Never combine facts from two different employers unless the supplied references explicitly say they belong together. Preserve employer attribution exactly. In particular, Omar's Spotify experience was chat-only; do not claim Spotify involved phone, email, SMS, or other channels. His multi-channel experience comes from his career across multiple roles, including phone work at Comdata. When the question is about Comdata, prefer the Comdata reference if supplied. The answer must be natural spoken language, concise, and usable directly in an interview.`},{role:'user',content:`Interview question:\n${body.transcript}\n\nProvided interview references:\n${referenceText||'(none)'}\n\nGenerate the best speakable answer.`}],temperature:.12,max_tokens:450,response_format:{type:'json_schema',json_schema:{name:'interview_response',strict:true,schema:{type:'object',additionalProperties:false,properties:{intent:{type:'string'},direction:{type:'array',items:{type:'string'}},say_this:{type:'string'},best_reference:{type:['string','null']},confidence:{type:'number',minimum:0,maximum:1}},required:['intent','direction','say_this','best_reference','confidence']}}}};}
async function callProvider(name,body){const cfg=providerConfig(name);if(!cfg?.key)return null;const resp=await fetch(cfg.url,{method:'POST',headers:{authorization:`Bearer ${cfg.key}`,'content-type':'application/json','HTTP-Referer':'http://3v0l.local','X-Title':'3V0L Interview Copilot'},body:JSON.stringify(buildPayload(body,cfg.model))});if(!resp.ok)throw new Error(`${cfg.label} ${resp.status}: ${await resp.text()}`);const data=await resp.json();const text=String(data?.choices?.[0]?.message?.content||'').trim();try{return {provider:name,result:JSON.parse(text)};}catch{}const cleaned=text.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();try{return {provider:name,result:JSON.parse(cleaned)};}catch{}const start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start>=0&&end>start){try{return {provider:name,result:JSON.parse(cleaned.slice(start,end+1))};}catch{}}throw new Error(`${cfg.label} returned unusable structured output`);}
async function callLLM(body){if(!llmEnabled)return null;let lastError=null;for(const name of providerOrder()){try{const out=await callProvider(name,body);if(out)return out;}catch(err){lastError=err;console.error(`${name} backend failed:`,err.message);}}if(lastError)throw lastError;return null;}
function llmStatus(){return {enabled:llmEnabled,primary:LLM_PRIMARY,cerebras:{configured:!!CEREBRAS_KEY,model:CEREBRAS_MODEL,url:CEREBRAS_URL},requesty:{configured:!!REQUESTY_KEY,model:REQUESTY_MODEL,url:REQUESTY_URL}};}
async function handleEvent(payload){const transcript=String(payload.transcript||payload.text||'').trim();if(!transcript)return state;const context=Array.isArray(payload.context)&&payload.context.length?payload.context.slice(0,8):relevantRefs(transcript);const base=heuristic(transcript,context);let ai=null;if(payload.final!==false&&llmEnabled){try{ai=await callLLM({transcript,speaker:payload.speaker||'interviewer',context});}catch(err){state.error=String(err.message||err);}}const merged=ai?.result||base;state={...state,lastEventAt:new Date().toISOString(),speaker:payload.speaker||'interviewer',transcript,final:payload.final!==false,intent:merged.intent||base.intent,direction:Array.isArray(merged.direction)?merged.direction:base.direction,sayThis:String(merged.say_this||base.sayThis||''),bestReference:merged.best_reference??base.bestReference,confidence:Number.isFinite(+merged.confidence)?+merged.confidence:base.confidence,provider:ai?.provider||(payload.provider||'local'),error:state.error||null};return state;}
setTranscriptHandler(handleEvent);
if(AUDIO_ENABLED){try{startSttServer();}catch(err){console.error('STT server failed:',err.message);}}
async function serveFile(path,type,res){try{const body=await readFile(join(dirname(fileURLToPath(import.meta.url)),path));res.writeHead(200,{'content-type':type,'cache-control':'no-store'});res.end(body);}catch{return json(res,404,{error:'not found'});}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end();}
if(url.pathname==='/health'&&req.method==='GET')return json(res,200,{ok:true,model:providerConfig(LLM_PRIMARY)?.model||CEREBRAS_MODEL,llm:llmStatus(),stt:sttStatus(),remoteConfigured:true,state});
if(url.pathname==='/state'&&req.method==='GET')return json(res,200,{...state,stt:sttStatus(),apis:{llm:llmStatus(),...sttProviderControls()}});
if(url.pathname==='/config'&&req.method==='GET')return json(res,200,{llm:llmStatus(),...sttProviderControls(),deepgramConfigured:!!process.env.DEEPGRAM_API_KEY,azureConfigured:!!process.env.AZURE_SPEECH_KEY,sttProvider:sttStatus().provider});
if(url.pathname==='/config'&&req.method==='POST'){const body=await parseBody(req);if(typeof body.llm==='boolean')llmEnabled=body.llm;if(typeof body.deepgram==='boolean')setSttProviderEnabled('deepgram',body.deepgram);if(typeof body.azure==='boolean')setSttProviderEnabled('azure',body.azure);return json(res,200,{llm:llmStatus(),...sttProviderControls(),deepgramConfigured:!!process.env.DEEPGRAM_API_KEY,azureConfigured:!!process.env.AZURE_SPEECH_KEY,sttProvider:sttStatus().provider});}
if(url.pathname==='/event'&&req.method==='POST')return json(res,200,await handleEvent(await parseBody(req)));
if(url.pathname==='/clear'&&req.method==='POST'){state={...state,lastEventAt:null,speaker:null,transcript:'',final:false,intent:'idle',direction:[],sayThis:'',bestReference:null,confidence:0,provider:'none',error:null};return json(res,200,state);}
if((url.pathname==='/remote'||url.pathname==='/remote.html')&&req.method==='GET')return serveFile('remote.html','text/html; charset=utf-8',res);
if(url.pathname==='/remote.webmanifest'&&req.method==='GET')return serveFile('remote.webmanifest','application/manifest+json; charset=utf-8',res);
if(url.pathname==='/remote-sw.js'&&req.method==='GET')return serveFile('remote-sw.js','application/javascript; charset=utf-8',res);
if(url.pathname==='/remote/info'&&req.method==='GET'){const hosts=lanAddresses();return json(res,200,{ok:true,port:PORT,hosts,remoteUrl:hosts[0]?`http://${hosts[0]}:${PORT}/remote`:`http://localhost:${PORT}/remote`,audioPort:Number(process.env.AUDIO_PORT||38472)});}
if(url.pathname==='/remote/action'&&req.method==='POST'){const body=await parseBody(req);if(!auth(body))return json(res,401,{error:'invalid remote PIN'});return json(res,200,{ok:true,command:enqueue(String(body.action||''),{value:body.value??null})});}
if(url.pathname==='/remote/commands'&&req.method==='GET'){const after=Number(url.searchParams.get('after')||0);return json(res,200,{commands:commands.filter(c=>c.id>after)});
}
return json(res,404,{error:'not found'});}catch(err){return json(res,500,{error:String(err.message||err)});}});
server.listen(PORT,HOST,()=>{const hosts=lanAddresses();console.log(`3V0L Copilot relay listening on http://${HOST}:${PORT}`);console.log(`3V0L Remote: ${hosts[0]?`http://${hosts[0]}:${PORT}/remote`:`http://localhost:${PORT}/remote`}`);console.log(`Audio/STT: ${hosts[0]?`${hosts[0]}:${Number(process.env.AUDIO_PORT||38472)}`:`localhost:${Number(process.env.AUDIO_PORT||38472)}`}`);console.log(`LLM primary: ${LLM_PRIMARY}`);console.log(`Cerebras: ${CEREBRAS_KEY?'configured':'not configured'}`);console.log(`Requesty fallback: ${REQUESTY_KEY?'configured':'not configured'}`);});